// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Valgapplikasjon;
using Valgapplikasjon.Data;

namespace Valgapplikasjon.Migrations.KandidaturDb
{
    [DbContext(typeof(KandidaturDbContext))]
    [Migration("20210312135346_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Valgapplikasjon.Models.MittKandidaturModel", b =>
                {
                    b.Property<int>("KandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrukerId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Sjekkboks")
                        .HasColumnType("bit");

                    b.HasKey("KandidatId");

                    b.ToTable("Kandidat");
                });
#pragma warning restore 612, 618
        }
    }
}
