// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Valgapplikasjon.Data;

namespace Valgapplikasjon.Migrations.KandidaturDb
{
    [DbContext(typeof(KandidaturDbContext))]
    partial class KandidaturDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Valgapplikasjon.Models.MittKandidaturModel", b =>
                {
                    b.Property<int>("KandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrukerId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Sjekkboks")
                        .HasColumnType("bit");

                    b.HasKey("KandidatId");

                    b.HasIndex("BrukerId")
                        .IsUnique()
                        .HasFilter("[BrukerId] IS NOT NULL");

                    b.ToTable("Kandidat");
                });
#pragma warning restore 612, 618
        }
    }
}
